DEBUG = False# Turns on debugging features in Flask
BCRYPT_LOG_ROUNDS = 12# Configuration for the Flask-Bcrypt extension
MAIL_FROM_EMAIL = "mohamed.khan@dubaiholding.com"# For use in application emails
BASIC_AUTH_USERNAME = "modelusername"
BASIC_AUTH_PASSWORD = "modelpassword"
DAMCHURPRED_USERNAME = "damchurnpredusername"
DAMCHURPRED_PASSWORD = "damchurnpredpassword"
DAMCHURPRED_DBSERVER = "tcp:sqlsvrdamprd.database.windows.net,1433"
DAMCHURPRED_DBNAME = "dbname"
DAMCHURPRED_DBUSER = "dbusername"
DAMCHURPRED_DBPWD = "dbpassword"
DHMODEL_DBSERVER = "tcp:sqlsvrjumdev.database.windows.net,1433"
DHMODEL_DBNAME = "2nddbname"
DHMODEL_DBUSER = "2nddbuser"
DHMODEL_DBPWD = "2nddbpassword"
RUNTYPE = "PROD"
